// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVlST0CaMqNKv_0k44XU2OfbYRVGspw20',
    appId: '1:326612037740:web:873732a763c5e56996e849',
    messagingSenderId: '326612037740',
    projectId: 'habittracker-fb9bd',
    authDomain: 'habittracker-fb9bd.firebaseapp.com',
    storageBucket: 'habittracker-fb9bd.appspot.com',
    measurementId: 'G-RL25XPWGE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaxQFLwFne6HBH4ZbTWZo_oSiiEdvANoI',
    appId: '1:326612037740:android:22e82d079b9a335196e849',
    messagingSenderId: '326612037740',
    projectId: 'habittracker-fb9bd',
    storageBucket: 'habittracker-fb9bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcBnOGTzH19QvgcFnsS_MFxy3p8UTUtcs',
    appId: '1:326612037740:ios:f2a6e847ecb8d36096e849',
    messagingSenderId: '326612037740',
    projectId: 'habittracker-fb9bd',
    storageBucket: 'habittracker-fb9bd.appspot.com',
    iosClientId: '326612037740-l3f3v2rufst3akn5o120km9t464mgsb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcBnOGTzH19QvgcFnsS_MFxy3p8UTUtcs',
    appId: '1:326612037740:ios:f2a6e847ecb8d36096e849',
    messagingSenderId: '326612037740',
    projectId: 'habittracker-fb9bd',
    storageBucket: 'habittracker-fb9bd.appspot.com',
    iosClientId: '326612037740-l3f3v2rufst3akn5o120km9t464mgsb2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppNew',
  );
}
